apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rpc
  labels:
    name: myapp
    type: front-end

spec:
  template:
    metadata:
      name: nginx-rpc
      labels:
        name: nginx
    spec:
      containers:
        - name: nginx-container
          image:  nginx
          ports:
            - containerPort: 80
  replicas: 4



    

